//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekt.Resources.TabsResources", typeof(TabsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatek VAT 0%.
        /// </summary>
        public static string nrTowarPodatek0 {
            get {
                return ResourceManager.GetString("nrTowarPodatek0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatek VAT 5%.
        /// </summary>
        public static string nrTowarPodatek5 {
            get {
                return ResourceManager.GetString("nrTowarPodatek5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatek VAT 8%.
        /// </summary>
        public static string nrTowarPodatek8 {
            get {
                return ResourceManager.GetString("nrTowarPodatek8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowy podatek VAT 23%.
        /// </summary>
        public static string nrTowarPodstawowyPodatek23 {
            get {
                return ResourceManager.GetString("nrTowarPodstawowyPodatek23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrum autoryzacji kart płatniczych.
        /// </summary>
        public static string rxCentrumKart {
            get {
                return ResourceManager.GetString("rxCentrumKart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrum obsługi ratalnej.
        /// </summary>
        public static string rxCentrumObRat {
            get {
                return ResourceManager.GetString("rxCentrumObRat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czynny podatnik VAT.
        /// </summary>
        public static string rxCzynnyVat {
            get {
                return ResourceManager.GetString("rxCzynnyVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj:.
        /// </summary>
        public static string rxDodaj {
            get {
                return ResourceManager.GetString("rxDodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dopisz notatke:.
        /// </summary>
        public static string rxDopiszNotatke {
            get {
                return ResourceManager.GetString("rxDopiszNotatke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drukuj:.
        /// </summary>
        public static string rxDrukuj {
            get {
                return ResourceManager.GetString("rxDrukuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string rxEmail {
            get {
                return ResourceManager.GetString("rxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy:.
        /// </summary>
        public static string rxKodPocztowy {
            get {
                return ResourceManager.GetString("rxKodPocztowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komplet.
        /// </summary>
        public static string rxKomplet {
            get {
                return ResourceManager.GetString("rxKomplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj:.
        /// </summary>
        public static string rxListaFakturDodaj {
            get {
                return ResourceManager.GetString("rxListaFakturDodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj fakturę marża.
        /// </summary>
        public static string rxListaFakturDodFm {
            get {
                return ResourceManager.GetString("rxListaFakturDodFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj fakturę sprzedaży.
        /// </summary>
        public static string rxListaFakturDodFs {
            get {
                return ResourceManager.GetString("rxListaFakturDodFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj rachunek sprzedaży.
        /// </summary>
        public static string rxListaFakturDodRs {
            get {
                return ResourceManager.GetString("rxListaFakturDodRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string rxListaFakturKolData {
            get {
                return ResourceManager.GetString("rxListaFakturKolData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent.
        /// </summary>
        public static string rxListaFakturKolKontrahent {
            get {
                return ResourceManager.GetString("rxListaFakturKolKontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer.
        /// </summary>
        public static string rxListaFakturKolNumer {
            get {
                return ResourceManager.GetString("rxListaFakturKolNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status dokumentu.
        /// </summary>
        public static string rxListaFakturKolStatus {
            get {
                return ResourceManager.GetString("rxListaFakturKolStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status fiskalny.
        /// </summary>
        public static string rxListaFakturKolStatusFis {
            get {
                return ResourceManager.GetString("rxListaFakturKolStatusFis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość brutto.
        /// </summary>
        public static string rxListaFakturKolWartoscBrutto {
            get {
                return ResourceManager.GetString("rxListaFakturKolWartoscBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość netto.
        /// </summary>
        public static string rxListaFakturKolWartoscNetto {
            get {
                return ResourceManager.GetString("rxListaFakturKolWartoscNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koryguj:.
        /// </summary>
        public static string rxListaFakturKoryguj {
            get {
                return ResourceManager.GetString("rxListaFakturKoryguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozlicz:.
        /// </summary>
        public static string rxListaFakturRozlicz {
            get {
                return ResourceManager.GetString("rxListaFakturRozlicz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string rxListaKontrahentowAdres {
            get {
                return ResourceManager.GetString("rxListaKontrahentowAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość.
        /// </summary>
        public static string rxListaKontrahentowMiejscowosc {
            get {
                return ResourceManager.GetString("rxListaKontrahentowMiejscowosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string rxListaKontrahentowNazwa {
            get {
                return ResourceManager.GetString("rxListaKontrahentowNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string rxListaKontrahentowNip {
            get {
                return ResourceManager.GetString("rxListaKontrahentowNip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string rxListaKontrahentowRodzaj {
            get {
                return ResourceManager.GetString("rxListaKontrahentowRodzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string rxListaKontrahentowSymbol {
            get {
                return ResourceManager.GetString("rxListaKontrahentowSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string rxListaKontrahentowTyp {
            get {
                return ResourceManager.GetString("rxListaKontrahentowTyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaliczna brutto.
        /// </summary>
        public static string rxListaTowarowDetalicznaBrutto {
            get {
                return ResourceManager.GetString("rxListaTowarowDetalicznaBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaliczna netto.
        /// </summary>
        public static string rxListaTowarowKolDetalicznaNetto {
            get {
                return ResourceManager.GetString("rxListaTowarowKolDetalicznaNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostepne.
        /// </summary>
        public static string rxListaTowarowKolDostepne {
            get {
                return ResourceManager.GetString("rxListaTowarowKolDostepne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurtowa brutto.
        /// </summary>
        public static string rxListaTowarowKolHurtowaBrutto {
            get {
                return ResourceManager.GetString("rxListaTowarowKolHurtowaBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurtowa netto.
        /// </summary>
        public static string rxListaTowarowKolHurtowaNetto {
            get {
                return ResourceManager.GetString("rxListaTowarowKolHurtowaNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.m..
        /// </summary>
        public static string rxListaTowarowKolJm {
            get {
                return ResourceManager.GetString("rxListaTowarowKolJm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string rxListaTowarowKolNazwa {
            get {
                return ResourceManager.GetString("rxListaTowarowKolNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerwacja.
        /// </summary>
        public static string rxListaTowarowKolRezerwacja {
            get {
                return ResourceManager.GetString("rxListaTowarowKolRezerwacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string rxListaTowarowKolRodzaj {
            get {
                return ResourceManager.GetString("rxListaTowarowKolRodzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan.
        /// </summary>
        public static string rxListaTowarowKolStan {
            get {
                return ResourceManager.GetString("rxListaTowarowKolStan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string rxListaTowarowKolSymbol {
            get {
                return ResourceManager.GetString("rxListaTowarowKolSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmontuj:.
        /// </summary>
        public static string rxListaTowarowRozmontuj {
            get {
                return ResourceManager.GetString("rxListaTowarowRozmontuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmontuj:.
        /// </summary>
        public static string rxListaTowarowZmontuj {
            get {
                return ResourceManager.GetString("rxListaTowarowZmontuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        public static string rxNazwa {
            get {
                return ResourceManager.GetString("rxNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pełna:.
        /// </summary>
        public static string rxNazwaPelna {
            get {
                return ResourceManager.GetString("rxNazwaPelna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP:.
        /// </summary>
        public static string rxNip {
            get {
                return ResourceManager.GetString("rxNip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr domu:.
        /// </summary>
        public static string rxNrDomu {
            get {
                return ResourceManager.GetString("rxNrDomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer EORI:.
        /// </summary>
        public static string rxNrEori {
            get {
                return ResourceManager.GetString("rxNrEori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr lokalu:.
        /// </summary>
        public static string rxNrLokalu {
            get {
                return ResourceManager.GetString("rxNrLokalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorca detaliczny.
        /// </summary>
        public static string rxOdbiorcaDetal {
            get {
                return ResourceManager.GetString("rxOdbiorcaDetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Państwo:.
        /// </summary>
        public static string rxPanstwo {
            get {
                return ResourceManager.GetString("rxPanstwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francja.
        /// </summary>
        public static string rxPanstwo_Francja {
            get {
                return ResourceManager.GetString("rxPanstwo_Francja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemcy.
        /// </summary>
        public static string rxPanstwo_Niemcy {
            get {
                return ResourceManager.GetString("rxPanstwo_Niemcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polska.
        /// </summary>
        public static string rxPanstwo_Polska {
            get {
                return ResourceManager.GetString("rxPanstwo_Polska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż:.
        /// </summary>
        public static string rxPokaż {
            get {
                return ResourceManager.GetString("rxPokaż", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popraw:.
        /// </summary>
        public static string rxPopraw {
            get {
                return ResourceManager.GetString("rxPopraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON:.
        /// </summary>
        public static string rxRegon {
            get {
                return ResourceManager.GetString("rxRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj:.
        /// </summary>
        public static string rxRodzaj {
            get {
                return ResourceManager.GetString("rxRodzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol:.
        /// </summary>
        public static string rxSymbol {
            get {
                return ResourceManager.GetString("rxSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towar.
        /// </summary>
        public static string rxTowar {
            get {
                return ResourceManager.GetString("rxTowar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutto.
        /// </summary>
        public static string rxTowarCennikBrutto {
            get {
                return ResourceManager.GetString("rxTowarCennikBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa ceny.
        /// </summary>
        public static string rxTowarCennikNazwaCeny {
            get {
                return ResourceManager.GetString("rxTowarCennikNazwaCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluta.
        /// </summary>
        public static string rxTowarCennikNazwaWaluta {
            get {
                return ResourceManager.GetString("rxTowarCennikNazwaWaluta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string rxTowarCennikNetto {
            get {
                return ResourceManager.GetString("rxTowarCennikNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTU_01 - Napoje alkoholowe.
        /// </summary>
        public static string rxTowarJPKVAT_01 {
            get {
                return ResourceManager.GetString("rxTowarJPKVAT_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTU_02 - Paliwa.
        /// </summary>
        public static string rxTowarJPKVAT_02 {
            get {
                return ResourceManager.GetString("rxTowarJPKVAT_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTU_03 - Odpady.
        /// </summary>
        public static string rxTowarJPKVAT_03 {
            get {
                return ResourceManager.GetString("rxTowarJPKVAT_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTU_04 - Wyroby tytoniowe.
        /// </summary>
        public static string rxTowarJPKVAT_04 {
            get {
                return ResourceManager.GetString("rxTowarJPKVAT_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (nie wymaga oznaczenia).
        /// </summary>
        public static string rxTowarJPKVAT_NieWymaga {
            get {
                return ResourceManager.GetString("rxTowarJPKVAT_NieWymaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja cen.
        /// </summary>
        public static string rxTowarKalkulacjaCen {
            get {
                return ResourceManager.GetString("rxTowarKalkulacjaCen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod towaru CN:.
        /// </summary>
        public static string rxTowarKodTowaruCN {
            get {
                return ResourceManager.GetString("rxTowarKodTowaruCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kpl..
        /// </summary>
        public static string rxTowarKpl {
            get {
                return ResourceManager.GetString("rxTowarKpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        public static string rxTowarOpis {
            get {
                return ResourceManager.GetString("rxTowarOpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozn. JPK VAT:.
        /// </summary>
        public static string rxTowarOznJPKVAT {
            get {
                return ResourceManager.GetString("rxTowarOznJPKVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKWiU:.
        /// </summary>
        public static string rxTowarPKWiU {
            get {
                return ResourceManager.GetString("rxTowarPKWiU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowa jednostka miary:.
        /// </summary>
        public static string rxTowarPodsJednostka {
            get {
                return ResourceManager.GetString("rxTowarPodsJednostka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka Vat:.
        /// </summary>
        public static string rxTowarStawkaVat {
            get {
                return ResourceManager.GetString("rxTowarStawkaVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWW:.
        /// </summary>
        public static string rxTowarSWW {
            get {
                return ResourceManager.GetString("rxTowarSWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szt..
        /// </summary>
        public static string rxTowarSzt {
            get {
                return ResourceManager.GetString("rxTowarSzt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        public static string rxTyp {
            get {
                return ResourceManager.GetString("rxTyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica:.
        /// </summary>
        public static string rxUlica {
            get {
                return ResourceManager.GetString("rxUlica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga.
        /// </summary>
        public static string rxUsluga {
            get {
                return ResourceManager.GetString("rxUsluga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dolnośląskie.
        /// </summary>
        public static string rxWojewodztwa_dolnoslaskie {
            get {
                return ResourceManager.GetString("rxWojewodztwa_dolnoslaskie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opolskie.
        /// </summary>
        public static string rxWojewodztwa_opolskie {
            get {
                return ResourceManager.GetString("rxWojewodztwa_opolskie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to śląskie.
        /// </summary>
        public static string rxWojewodztwa_slaskie {
            get {
                return ResourceManager.GetString("rxWojewodztwa_slaskie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo:.
        /// </summary>
        public static string rxWojewodztwo {
            get {
                return ResourceManager.GetString("rxWojewodztwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona WWW:.
        /// </summary>
        public static string rxWWW {
            get {
                return ResourceManager.GetString("rxWWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypisz dokument:.
        /// </summary>
        public static string rxWypiszDokument {
            get {
                return ResourceManager.GetString("rxWypiszDokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturę VAT sprzedaży.
        /// </summary>
        public static string rxWypiszDokument_FaktureVatSprze {
            get {
                return ResourceManager.GetString("rxWypiszDokument_FaktureVatSprze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon imienny.
        /// </summary>
        public static string rxWypiszDokument_ParagonImienny {
            get {
                return ResourceManager.GetString("rxWypiszDokument_ParagonImienny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rachunek sprzedaży.
        /// </summary>
        public static string rxWypiszDokument_Rachunek {
            get {
                return ResourceManager.GetString("rxWypiszDokument_Rachunek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie do dostawcy.
        /// </summary>
        public static string rxWypiszDokument_ZamowienieDoDostawcy {
            get {
                return ResourceManager.GetString("rxWypiszDokument_ZamowienieDoDostawcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie od Klienta.
        /// </summary>
        public static string rxWypiszDokument_ZamowienieOdKlienta {
            get {
                return ResourceManager.GetString("rxWypiszDokument_ZamowienieOdKlienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string rxWystawFaktureAnuluj {
            get {
                return ResourceManager.GetString("rxWystawFaktureAnuluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia dostawy.
        /// </summary>
        public static string rxWystawFaktureDataZakonczenia {
            get {
                return ResourceManager.GetString("rxWystawFaktureDataZakonczenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj i wstaw kontrahenta.
        /// </summary>
        public static string rxWystawFaktureDodajIWstawKontrahenta {
            get {
                return ResourceManager.GetString("rxWystawFaktureDodajIWstawKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do zapłaty: 0,00 PLN.
        /// </summary>
        public static string rxWystawFaktureDoZaplaty {
            get {
                return ResourceManager.GetString("rxWystawFaktureDoZaplaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS.
        /// </summary>
        public static string rxWystawFaktureFS {
            get {
                return ResourceManager.GetString("rxWystawFaktureFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotówka:.
        /// </summary>
        public static string rxWystawFaktureGotowka {
            get {
                return ResourceManager.GetString("rxWystawFaktureGotowka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredyt kupiecki:.
        /// </summary>
        public static string rxWystawFaktureKredyt {
            get {
                return ResourceManager.GetString("rxWystawFaktureKredyt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kontrahentów.
        /// </summary>
        public static string rxWystawFaktureListaKontrahentow {
            get {
                return ResourceManager.GetString("rxWystawFaktureListaKontrahentow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabywca.
        /// </summary>
        public static string rxWystawFaktureNabywca {
            get {
                return ResourceManager.GetString("rxWystawFaktureNabywca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrał(a):.
        /// </summary>
        public static string rxWystawFaktureOdebral {
            get {
                return ResourceManager.GetString("rxWystawFaktureOdebral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jas Kapela.
        /// </summary>
        public static string rxWystawFaktureOdebralJas {
            get {
                return ResourceManager.GetString("rxWystawFaktureOdebralJas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord Wejder.
        /// </summary>
        public static string rxWystawFaktureOdebralWaider {
            get {
                return ResourceManager.GetString("rxWystawFaktureOdebralWaider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż.
        /// </summary>
        public static string rxWystawFakturePokaz {
            get {
                return ResourceManager.GetString("rxWystawFakturePokaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        public static string rxWystawFakturePomoc {
            get {
                return ResourceManager.GetString("rxWystawFakturePomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popraw.
        /// </summary>
        public static string rxWystawFakturePopraw {
            get {
                return ResourceManager.GetString("rxWystawFakturePopraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedpłata:.
        /// </summary>
        public static string rxWystawFakturePrzedplata {
            get {
                return ResourceManager.GetString("rxWystawFakturePrzedplata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelew:.
        /// </summary>
        public static string rxWystawFakturePrzelew {
            get {
                return ResourceManager.GetString("rxWystawFakturePrzelew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstaw kontrahenta jednorazowego.
        /// </summary>
        public static string rxWystawFaktureWstawKontrahenta {
            get {
                return ResourceManager.GetString("rxWystawFaktureWstawKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystawił(a):.
        /// </summary>
        public static string rxWystawFaktureWystawil {
            get {
                return ResourceManager.GetString("rxWystawFaktureWystawil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan Kowalski.
        /// </summary>
        public static string rxWystawFaktureWystawilKowalski {
            get {
                return ResourceManager.GetString("rxWystawFaktureWystawilKowalski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrzej Nowak.
        /// </summary>
        public static string rxWystawFaktureWystawilNowa {
            get {
                return ResourceManager.GetString("rxWystawFaktureWystawilNowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string rxWystawFaktureZapisz {
            get {
                return ResourceManager.GetString("rxWystawFaktureZapisz", resourceCulture);
            }
        }
    }
}
